Xpresso/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from horror_show.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('horror_show/', include('horror_show.urls', namespace='horror_show')),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path("", include("horror_show.urls")),
]

horror_show/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'horror_show'

urlpatterns = [
    # post views
    path(
        '',
        views.post_list,
        name='post_list'
    ),
    # path('', views.PostListView.as_view(), name='post_list'),
    path(
        'tag/<slug:tag_slug>/',
        views.post_list,
        name='post_list_by_tag'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'
    ),
    path(
        '<int:post_id>/share/',
        views.post_share,
        name='post_share'
    ),
    path(
        '<int:post_id>/comment/',
        views.post_comment,
        name='post_comment'
    ),
    path(
        'feed/',
        LatestPostsFeed(),
        name='post_feed'
    ),
    path(
        'search/',
        views.post_search,
        name='post_search'
    ),
]

horror_show/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='horror_posts'
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )

    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.

    class Meta:
        ordering = ['-publish']
        # indexes = [
        #     models.Index(fields=['-publish']),
        # ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'horror_show:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )

    tags = TaggableManager()


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
        models.Index(
            fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

horror_show/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )


class SearchForm(forms.Form):
    query = forms.CharField()

horror_show/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# from django.views.generic import ListView
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}\'s comments: {cd['comments']}"
            send_mail(
                subject,
                message,
                'your_account@gmail.com',
                [cd['to']]
            )
            sent = True
    else:
        form = EmailPostForm()
    return render(
        request,
        'horror_show/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent
        }
    )

# class PostListView(ListView):
#     """
#     Alternative post list view
#     """
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'horror_show/post/list.html'


def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Pagination with 10 posts per page
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        'horror_show/post/list.html',
        {
            'posts': posts,
            'tag': tag
        },
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(
        request,
        'horror_show/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'form': form,
            'similar_posts': similar_posts
        }
    )


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(
        request,
        'horror_show/post/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment
        }
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')

    return render(
        request,
        'horror_show/post/search.html',
        {
            'form': form,
            'query': query,
            'results': results
        }
    )

horror_show/templates/horror_show/post/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Comment</title>
</head>
<body>
    {% extends "horror_show/base.html" %}

    {% block title %}Add A Comment{% endblock %}

    {% block content %}
        {% if comment %}
            <h2>Your comment has been added.</h2>
            <p><a href="{{ post.get_absolute_url }}">Back To The Post</a></p>
        {% else %}
            {% include "horror_show/post/includes/comment_form.html" %}
        {% endif %}
    {% endblock %}
</body>
</html>

horror_show/templates/horror_show/post/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
    {% extends "horror_show/base.html" %}
    {% load blog_tags %}

    {% block title %}{{ post.title }}{% endblock %}

    {% block content %}
        <h1>{{ post.title }}</h1>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown }}
        <p>
            <a href="{% url "horror_show:post_share" post.id %}">
                Share This Post
            </a>
        </p>

        <h2>Similar posts</h2>
        {% for post in similar_posts %}
            <p>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </p>
        {% empty %}
            There are no similar posts yet.
        {% endfor %}

        {% with comments.count as total_comments %}
            <h2>
                {{ total_comments }} comment{{ total_comments|pluralize }}
            </h2>
        {% endwith %}
        {% for comment in comments %}
            <div class="comment">
                <p class="info">
                    Comment {{ forloop.counter }} by {{ comment.name }}
                    {{ comment.created }}
                </p>
                {{ comment.body|linebreaks }}
            </div>
        {% empty %}
            <p>There are no comments.</p>
        {% endfor %}
        {% include "horror_show/post/includes/comment_form.html" %}
    {% endblock %}
</body>
</html>

horror_show/templates/horror_show/post/latest_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Latest Posts</title>
</head>
<body>
    <ul>
        {% for post in latest_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

horror_show/templates/horror_show/post/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List</title>
</head>
<body>
    {% extends "horror_show/base.html" %}
    {% load blog_tags %}
    
    {% block title %}Horror Show{% endblock %}
    
    {% block content %}
        <h1>Horror Show</h1>
        {% if tag %}
            <h2>Posts tagged with "{{ tag.name }}"</h2>
        {% endif %}
        {% for post in posts %}
            <h2>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h2>
            {% for tag in post.tags.all %}
                <a href="{% url "horror_show:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
            <p class="date">
                Published {{ post.publish }} by {{ post.author }}
            </p>
            {{ post.body|markdown|truncatewords_html:30 }}
        {% endfor %}
        {% include "pagination.html" with page=posts %}
    {% endblock %}
</body>
</html>

horror_show/templates/horror_show/post/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
    {% extends "horror_show/base.html" %}
    {% load blog_tags %}

    {% block title %}Search{% endblock %}

    {% block content %}
        {% if query %}
            <h1>Posts containing "{{ query }}"</h1>
            <h3>
                {% with results.count as total_results %}
                    Found {{ total_results }} result{{ total_results|pluralize }}
                {% endwith %}
            </h3>
            {% for post in results %}
                <h4>
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h4>
                {{ post.body|markdown|truncatewords_html:12 }}
            {% empty %}
                <p>There are no results for your query.</p>
            {% endfor %}
            <p><a href="{% url "horror_show:post_search" %}">Search again</a></p>
        {% else %}
            <h1>Search for posts</h1>
            <form method="get">
                {{ form.as_p }}
                <input type="submit" value="Search">
            </form>
        {% endif %}
    {% endblock %}
</body>
</html>

horror_show/templates/horror_show/post/share.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Share</title>
</head>
<body>
    {% extends "horror_show/base.html" %}

    {% block title %}Share A Post{% endblock %}

    {% block content %}
        {% if sent %}
            <h1>E-mail Successfully Sent!</h1>
            <p>
                "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
            </p>
        {% else %}
            <h1>Share "{{ post.title }}" By E-mail</h1>
            <form method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Send e-mail">
            </form>
        {% endif %}
    {% endblock %}
</body>
</html>